# Generated by Django 3.1.5 on 2021-01-16 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=254, null=True)),
                ('profile_image', models.CharField(blank=True, max_length=254, null=True)),
                ('cv_url', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=254, null=True)),
                ('linkedin_profile', models.CharField(blank=True, max_length=254, null=True)),
                ('instagram_profile', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.CharField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(blank=True, max_length=254, null=True)),
                ('company', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin_profile', models.CharField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.CharField(max_length=254)),
                ('full_name', models.CharField(max_length=254)),
                ('position', models.CharField(max_length=254)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('is_show', models.BooleanField(default=False)),
                ('linkedin_profile', models.CharField(blank=True, max_length=254, null=True)),
                ('instagram_profile', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('meet_url', models.CharField(blank=True, max_length=254, null=True)),
                ('testimony', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.client')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.consultant')),
            ],
        ),
    ]
