# Generated by Django 3.1.7 on 2021-09-04 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('full_name', models.CharField(max_length=254)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='profile-image/%Y/%m/%d/')),
                ('title', models.CharField(max_length=254)),
                ('cv_url', models.URLField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=254)),
                ('linkedin_profile', models.URLField(blank=True, max_length=254, null=True)),
                ('instagram_profile', models.URLField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'core_client',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'core_company',
            },
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='profile-image/%Y/%m/%d/')),
                ('full_name', models.CharField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin_profile', models.URLField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('is_cv', models.BooleanField(blank=True, null=True)),
                ('is_interview', models.BooleanField(blank=True, null=True)),
                ('cv_price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('interview_price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('start_date', models.DateField()),
                ('experience', models.TextField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('role_expertise', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_consultant',
            },
        ),
        migrations.CreateModel(
            name='ConsultantSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('type', models.CharField(blank=True, choices=[('INTERVIEW', 'Interview'), ('CV', 'CV')], max_length=254, null=True)),
                ('is_booked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'core_consultant_schedule',
            },
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('client_problem', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('INTERVIEW', 'Interview'), ('CV', 'CV')], max_length=254)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False, editable=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('testimony', models.TextField(blank=True, null=True)),
                ('testimony_proof', models.FileField(blank=True, null=True, upload_to='testimony-proof/%Y/%m/%d/')),
                ('show_testimony', models.BooleanField(default=False)),
                ('rating', models.IntegerField(choices=[(1, 'Sangat Tidak Puas'), (2, 'Tidak Puas'), (3, 'Biasa'), (4, 'Puas'), (5, 'Sangat Puas')], default=3)),
                ('show_rating', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_meet',
            },
        ),
        migrations.CreateModel(
            name='MeetPayroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('for_consultant', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('for_company', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('consultant_paid_proof', models.FileField(blank=True, null=True, upload_to='consultant-paid-proof/%Y/%m/%d/')),
                ('is_consultant_paid', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_meet_payroll',
            },
        ),
        migrations.CreateModel(
            name='MidtransLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('transaction_time', models.CharField(blank=True, max_length=254, null=True)),
                ('transaction_status', models.CharField(blank=True, max_length=254, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=254, null=True)),
                ('store', models.CharField(blank=True, max_length=254, null=True)),
                ('status_message', models.CharField(blank=True, max_length=254, null=True)),
                ('status_code', models.CharField(blank=True, max_length=254, null=True)),
                ('signature_key', models.CharField(blank=True, max_length=254, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=254, null=True)),
                ('payment_code', models.CharField(blank=True, max_length=254, null=True)),
                ('order_id', models.CharField(blank=True, max_length=254, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=254, null=True)),
                ('gross_amount', models.CharField(blank=True, max_length=254, null=True)),
                ('currency', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'core_midtrans_log',
            },
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('order_id', models.CharField(blank=True, editable=False, max_length=254, null=True, unique=True)),
                ('unique_code', models.CharField(blank=True, editable=False, max_length=254, null=True, unique=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_name', models.CharField(blank=True, max_length=254, null=True)),
                ('client_phone_number', models.CharField(blank=True, max_length=254, null=True)),
                ('client_problem', models.TextField(blank=True, null=True)),
                ('client_resume_url', models.URLField(blank=True, max_length=254, null=True)),
                ('consultant_id', models.IntegerField(blank=True, null=True)),
                ('consultant_name', models.CharField(blank=True, max_length=254, null=True)),
                ('consultant_price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('consultant_schedule_id', models.IntegerField(blank=True, null=True)),
                ('consultant_type', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'core_order_log',
            },
        ),
        migrations.AddIndex(
            model_name='midtranslog',
            index=models.Index(fields=['transaction_id', 'order_id', 'transaction_status'], name='core_midtra_transac_924f8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='midtranslog',
            unique_together={('transaction_id', 'order_id', 'transaction_status')},
        ),
        migrations.AddField(
            model_name='meetpayroll',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meet_payrolls', to='core.consultant'),
        ),
        migrations.AddField(
            model_name='meetpayroll',
            name='meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meet_payrolls', to='core.meet'),
        ),
        migrations.AddField(
            model_name='meet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meets', to='core.client'),
        ),
        migrations.AddField(
            model_name='meet',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meets', to='core.consultant'),
        ),
        migrations.AddField(
            model_name='meet',
            name='payment_proof',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meets', to='core.midtranslog'),
        ),
        migrations.AddField(
            model_name='consultantschedule',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consultant_schedules', to='core.consultant'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consultants', to='core.company'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='meet',
            index=models.Index(fields=['client_id', 'consultant_id', 'payment_proof_id'], name='core_meet_client__57da5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meet',
            unique_together={('client_id', 'consultant_id', 'payment_proof_id')},
        ),
    ]
