# Generated by Django 3.1.6 on 2021-02-06 10:33

import app.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('full_name', models.CharField(max_length=254)),
                ('profile_image', models.FileField(blank=True, null=True, storage=app.storage_backends.PublicMediaStorage(), upload_to='')),
                ('title', models.CharField(max_length=254)),
                ('cv_url', models.URLField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=254)),
                ('linkedin_profile', models.URLField(blank=True, max_length=254, null=True)),
                ('instagram_profile', models.URLField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'core_client',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'core_company',
            },
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('profile_image', models.FileField(blank=True, null=True, storage=app.storage_backends.PublicMediaStorage(), upload_to='')),
                ('full_name', models.CharField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin_profile', models.URLField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('is_cv', models.BooleanField(blank=True, null=True)),
                ('is_interview', models.BooleanField(blank=True, null=True)),
                ('cv_price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('interview_price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('start_date', models.DateField()),
                ('experience', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.company')),
            ],
            options={
                'db_table': 'core_consultant',
            },
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('type', models.CharField(choices=[('INTERVIEW', 'Interview'), ('CV', 'CV')], max_length=254)),
                ('datetime', models.DateTimeField()),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_proof', models.FileField(blank=True, null=True, storage=app.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('meet_url', models.URLField(blank=True, max_length=254, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('testimony', models.TextField(blank=True, null=True)),
                ('testimony_proof', models.FileField(blank=True, null=True, storage=app.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('show_testimony', models.BooleanField(default=False)),
                ('rating', models.IntegerField(choices=[(1, 'Sangat Tidak Puas'), (2, 'Tidak Puas'), (3, 'Biasa'), (4, 'Puas'), (5, 'Sangat Puas')], default=3)),
                ('show_rating', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.client')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.consultant')),
            ],
            options={
                'db_table': 'core_meet',
            },
        ),
        migrations.CreateModel(
            name='MeetPayroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('for_consultant', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('for_company', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('consultant_paid_proof', models.FileField(blank=True, null=True, storage=app.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('is_consultant_paid', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.consultant')),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meet')),
            ],
            options={
                'db_table': 'core_meet_payroll',
            },
        ),
        migrations.CreateModel(
            name='MeetPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('due_datetime', models.DateTimeField()),
                ('method', models.CharField(blank=True, choices=[('BCA', 'Transfer BCA'), ('BNI', 'Transfer BNI')], max_length=254, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('admin_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.meet')),
            ],
            options={
                'db_table': 'core_meet_payment',
            },
        ),
        migrations.CreateModel(
            name='ConsultantSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.consultant')),
            ],
            options={
                'db_table': 'core_consultant_schedule',
            },
        ),
    ]
