# Generated by Django 3.1.5 on 2021-01-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('linkedin_profile', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('is_active', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('experience', models.TextField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='person',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
