# Generated by Django 3.1.6 on 2021-02-07 10:37

import app.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='datetime',
        ),
        migrations.AddField(
            model_name='meet',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meet',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consultants', to='core.company'),
        ),
        migrations.AlterField(
            model_name='consultantschedule',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consultant_schedules', to='core.consultant'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meets', to='core.client'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meets', to='core.consultant'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='testimony_proof',
            field=models.FileField(blank=True, null=True, storage=app.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='meetpayment',
            name='meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meet_payments', to='core.meet'),
        ),
        migrations.AlterField(
            model_name='meetpayroll',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meet_payrolls', to='core.consultant'),
        ),
        migrations.AlterField(
            model_name='meetpayroll',
            name='meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meet_payrolls', to='core.meet'),
        ),
    ]
