# Generated by Django 3.1.5 on 2021-01-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_show',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
