# Generated by Django 3.1.5 on 2021-01-17 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210117_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='order',
        ),
    ]
