# Generated by Django 3.1.6 on 2021-02-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210207_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='role_expertise',
            field=models.TextField(blank=True, null=True),
        ),
    ]
