# Generated by Django 3.1.5 on 2021-01-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210117_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='is_complete',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
