# Generated by Django 3.1.5 on 2021-01-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210116_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
