# Generated by Django 3.1.5 on 2021-01-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_interview_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
