# Generated by Django 3.1.6 on 2021-02-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_consultantschedule_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultantschedule',
            name='end_date',
        ),
    ]
