# Generated by Django 3.1.5 on 2021-01-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210117_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='show_testimony',
            field=models.BooleanField(default=False),
        ),
    ]
