# Generated by Django 3.1.6 on 2021-03-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_consultantschedule_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_name', models.CharField(blank=True, max_length=254, null=True)),
                ('client_phone_number', models.CharField(blank=True, max_length=254, null=True)),
                ('client_problem', models.TextField(blank=True, null=True)),
                ('client_resume_url', models.URLField(blank=True, max_length=254, null=True)),
                ('consultant_id', models.IntegerField()),
                ('consultant_schedule_id', models.IntegerField()),
            ],
            options={
                'db_table': 'core_order_log',
            },
        ),
    ]
