# Generated by Django 3.1.5 on 2021-01-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210116_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='consultant_name',
        ),
        migrations.AddField(
            model_name='interview',
            name='meet_url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
