# Generated by Django 3.1.5 on 2021-01-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_interview_show_testimony'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='consultant',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='client',
            name='title',
            field=models.CharField(default='Fresh Graduate', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='client',
            table='core_client',
        ),
        migrations.AlterModelTable(
            name='consultant',
            table='core_consultant',
        ),
        migrations.AlterModelTable(
            name='interview',
            table='core_interview',
        ),
        migrations.AlterModelTable(
            name='teammember',
            table='core_teammember',
        ),
    ]
