# Generated by Django 3.1.6 on 2021-03-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_orderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='consultant_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='consultant_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='consultant_type',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='consultant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='consultant_schedule_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
