# Generated by Django 3.1.6 on 2021-03-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210320_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='unique_code',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True, unique=True),
        ),
    ]
