# Generated by Django 3.1.5 on 2021-01-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210117_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='testimony_proof',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
