# Generated by Django 3.1.7 on 2021-03-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_orderlog_unique_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidtransLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('transaction_time', models.CharField(blank=True, max_length=254, null=True)),
                ('transaction_status', models.CharField(blank=True, max_length=254, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=254, null=True)),
                ('store', models.CharField(blank=True, max_length=254, null=True)),
                ('status_message', models.CharField(blank=True, max_length=254, null=True)),
                ('status_code', models.CharField(blank=True, max_length=254, null=True)),
                ('signature_key', models.CharField(blank=True, max_length=254, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=254, null=True)),
                ('payment_code', models.CharField(blank=True, max_length=254, null=True)),
                ('order_id', models.CharField(blank=True, max_length=254, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=254, null=True)),
                ('gross_amount', models.CharField(blank=True, max_length=254, null=True)),
                ('currency', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'core_midtrans_log',
            },
        ),
        migrations.AddIndex(
            model_name='midtranslog',
            index=models.Index(fields=['transaction_id', 'order_id', 'transaction_status'], name='core_midtra_transac_924f8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='midtranslog',
            unique_together={('transaction_id', 'order_id', 'transaction_status')},
        ),
    ]
