# Generated by Django 3.1.5 on 2021-01-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_interview_testimony_proof'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consultant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={},
        ),
    ]
