# Generated by Django 3.1.7 on 2021-03-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210320_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='order_id',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True, unique=True),
        ),
    ]
