# Generated by Django 3.1.5 on 2021-01-17 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_auto_20210117_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type',
                 models.CharField(blank=True, choices=[('INTERVIEW', 'Interview'), ('CV', 'CV')], max_length=254,
                                  null=True)),
                ('datetime', models.DateTimeField()),
                ('is_complete', models.BooleanField(default=False)),
                ('meet_url', models.CharField(blank=True, max_length=254, null=True)),
                ('testimony', models.TextField(blank=True, null=True)),
                ('testimony_proof', models.CharField(blank=True, max_length=254, null=True)),
                ('show_testimony', models.BooleanField(default=False)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('show_rating', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.client')),
            ],
            options={
                'db_table': 'core_meet',
            },
        ),
        migrations.RenameField(
            model_name='consultant',
            old_name='price',
            new_name='cv_price',
        ),
        migrations.AddField(
            model_name='consultant',
            name='interview_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='is_cv',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='is_interview',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.AddField(
            model_name='meet',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.consultant'),
        ),
    ]
