# Generated by Django 3.1.7 on 2021-03-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_midtranslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midtranslog',
            name='order_id',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='midtranslog',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
