# Generated by Django 3.1.5 on 2021-01-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210116_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
