# Generated by Django 3.1.5 on 2021-01-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210116_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='is_show',
            field=models.BooleanField(default=None),
        ),
    ]
