# Generated by Django 3.1.7 on 2021-03-20 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_orderlog_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='paid_proof',
        ),
        migrations.AddField(
            model_name='meet',
            name='client_problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meet',
            name='payment_proof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meets', to='core.midtranslog'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
