# Generated by Django 3.1.5 on 2021-01-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210117_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Sangat Tidak Puas'), (2, 'Tidak Puas'), (3, 'Biasa'), (4, 'Puas'), (5, 'Sangat Puas')], default=3),
        ),
    ]
