# Generated by Django 3.1.5 on 2021-01-16 11:56

from django.db import migrations


def postgres_migration_prep_team_member_order_field(apps, schema_editor):
    user_model = apps.get_model("core", "TeamMember")
    field = "order"

    filter_param = {"{}__exact".format(field): 1}
    update_param = {field: None}
    user_model.objects.filter(**filter_param).update(**update_param)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0012_auto_20210116_1147'),
    ]

    operations = [
        migrations.RunPython(
            postgres_migration_prep_team_member_order_field, migrations.RunPython.noop
        )
    ]
