# Generated by Django 3.1.7 on 2021-03-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210320_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='meet',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meet',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meet',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
