# Generated by Django 3.1.7 on 2021-03-20 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210320_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='is_paid',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='meet',
            name='payment_proof',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meets', to='core.midtranslog'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='meet',
            unique_together={('client_id', 'consultant_id', 'payment_proof_id')},
        ),
        migrations.AddIndex(
            model_name='meet',
            index=models.Index(fields=['client_id', 'consultant_id', 'payment_proof_id'], name='core_meet_client__57da5f_idx'),
        ),
    ]
