# Generated by Django 3.1.5 on 2021-01-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210118_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='meet',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='meet',
            name='modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
