# Generated by Django 3.1.7 on 2021-03-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210320_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantschedule',
            name='type',
            field=models.CharField(blank=True, choices=[('INTERVIEW', 'Interview'), ('CV', 'CV')], max_length=254, null=True),
        ),
    ]
