# Generated by Django 3.1.5 on 2021-01-18 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210118_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('due_datetime', models.DateTimeField()),
                ('method', models.CharField(blank=True, choices=[('BCA', 'Transfer BCA'), ('BNI', 'Transfer BNI')], max_length=254, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('admin_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.meet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
