# Generated by Django 3.1.7 on 2021-03-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_consultantschedule_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='meet_url',
        ),
        migrations.DeleteModel(
            name='MeetPayment',
        ),
    ]
