# Generated by Django 3.1.5 on 2021-01-18 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210119_0636'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teammember',
            table='core_team_member',
        ),
    ]
