# Generated by Django 3.1.5 on 2021-01-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210119_0637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='MeetPayment',
        ),
        migrations.AlterModelTable(
            name='meetpayment',
            table='core_meet_payment',
        ),
    ]
