# Generated by Django 3.1.5 on 2021-01-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_meetpayroll_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetpayroll',
            name='consultant_paid_proof',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
    ]
