# Generated by Django 3.1.5 on 2021-01-19 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_meetpayroll_consultant_paid_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetpayroll',
            name='consultant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.consultant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetpayroll',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meet'),
        ),
    ]
