# Generated by Django 3.1.5 on 2021-01-19 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210119_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetpayroll',
            old_name='payment',
            new_name='meet',
        ),
    ]
