# Generated by Django 3.1.5 on 2021-01-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210119_0759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
