# Generated by Django 3.1.5 on 2021-01-22 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210119_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
