# Generated by Django 3.1.5 on 2021-01-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_company'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='core_company',
        ),
    ]
