# Generated by Django 3.1.5 on 2021-01-23 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210123_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.company'),
            preserve_default=False,
        ),
    ]
