# Generated by Django 3.1.5 on 2021-01-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210123_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='name',
        ),
    ]
