# Generated by Django 3.1.5 on 2021-01-23 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210123_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.consultant')),
            ],
            options={
                'db_table': 'core_consultant_schedule',
            },
        ),
    ]
