# Generated by Django 3.1.5 on 2021-01-23 08:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_consultantschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultantschedule',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='consultantschedule',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 23, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
