# Generated by Django 3.1.6 on 2021-02-06 09:18

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210123_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_image',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='profile_image',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='paid_proof',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='testimony_proof',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetpayroll',
            name='consultant_paid_proof',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
