# Generated by Django 3.1.7 on 2021-04-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('items', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link_to_product', models.URLField(blank=True, max_length=254, null=True)),
                ('slug', models.SlugField(blank=True, default=models.CharField(max_length=100), max_length=255, null=True, verbose_name='CMS Product')),
            ],
            options={
                'db_table': 'cms_product',
            },
        ),
    ]
