# Generated by Django 3.1.7 on 2021-09-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='banner/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=254, null=True)),
                ('cta_text', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cms_banner',
            },
        ),
    ]
