# Generated by Django 3.1.7 on 2021-04-03 00:52

import app.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='link_to_product',
            new_name='link',
        ),
        migrations.AddField(
            model_name='product',
            name='cta_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, storage=app.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
