# Generated by Django 3.1.6 on 2021-02-06 10:33

import app.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('profile_image', models.FileField(blank=True, null=True, storage=app.storage_backends.PublicMediaStorage(), upload_to='')),
                ('full_name', models.CharField(max_length=254)),
                ('position', models.CharField(max_length=254)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('type', models.CharField(choices=[('FOUNDER', 'Founder'), ('CO-FOUNDER', 'Co Founder'), ('FULL-TIME', 'Full time'), ('PART-TIME', 'Part time'), ('INTERN', 'Intern')], max_length=254)),
                ('linkedin_profile', models.URLField(blank=True, max_length=254, null=True)),
                ('instagram_profile', models.URLField(blank=True, max_length=254, null=True)),
                ('is_show', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'office_employee',
            },
        ),
        migrations.CreateModel(
            name='EmployeePayroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('date', models.DateField()),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('employee_paid_proof', models.FileField(blank=True, null=True, storage=app.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('is_employee_paid', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='office.employee')),
            ],
            options={
                'db_table': 'office_employee_payroll',
            },
        ),
    ]
