# Generated by Django 3.1.5 on 2021-01-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_auto_20210119_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('FOUNDER', 'Founder'), ('CO-FOUNDER', 'Co Founder'), ('FULL-TIME', 'Full time'), ('PART-TIME', 'Part time'), ('INTERN', 'Intern')], default='FOUNDER', max_length=254),
            preserve_default=False,
        ),
    ]
