# Generated by Django 3.1.5 on 2021-01-19 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_auto_20210119_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayroll',
            name='date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
