# Generated by Django 3.1.6 on 2021-02-06 09:25

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_employeepayroll_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeepayroll',
            name='employee_paid_proof',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
