# Generated by Django 3.1.6 on 2021-03-13 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'seo_job_post_company',
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('position', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=254)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('min_qualification', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('link_to_apply', models.URLField(blank=True, max_length=254, null=True)),
                ('recruiter_email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_posts', to='seo.jobpostcompany')),
            ],
            options={
                'db_table': 'seo_job_post',
            },
        ),
    ]
