# Generated by Django 3.1.6 on 2021-03-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_jobpost_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='slug',
            field=models.SlugField(default='None <django.db.models.fields.CharField> <django.db.models.fields.CharField> <django.db.models.fields.CharField>', max_length=255, verbose_name='Job Post Slug'),
        ),
        migrations.AddField(
            model_name='jobpostcompany',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100, unique=True), max_length=255, verbose_name='Job Post Company Slug'),
        ),
        migrations.AlterField(
            model_name='jobpostcompany',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
