# Generated by Django 3.1.6 on 2021-03-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_auto_20210313_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='slug',
            field=models.SlugField(blank=True, default='None <django.db.models.fields.CharField> <django.db.models.fields.CharField> <django.db.models.fields.CharField>', max_length=255, null=True, verbose_name='Job Post Slug'),
        ),
        migrations.AlterField(
            model_name='jobpostcompany',
            name='slug',
            field=models.SlugField(blank=True, default=models.CharField(max_length=100), max_length=255, null=True, verbose_name='Job Post Company Slug'),
        ),
    ]
